AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recognize the characters in the image uploaded to S3 bucket using OCR.
Parameters:
  ImageBucketName:
    Type: String
    Description: "Name of the Bucket to store the images. Note: It should be lowecase letters, numbers or hypen and between 3 and 63 characters."
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
  TextTableName:
    Description: "Name of the DynamoDB table to store the recognized text. Note: It should be alphanumeric, underscore or hypen and between 3 and 63 characters."
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-_]*[a-zA-Z0-9]$
    Type: String
Outputs:
  ImageBucket:
    Description: S3 Bucket where the images needs to be uploaded.
    Value:
      Ref: ImageBucketName
  OutputTextTable:
    Description: DynamoDB table where the text will be stored.
    Value:
      Ref: TextTableName
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda-ocr
      MemorySize: 1536
      Timeout: 300
      Environment:
        Variables:
          TESSDATA_PREFIX: ''
          DYNAMODB_TABLE:
            Ref: TextTableName
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: ImageBucketName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TextTableName
      Events:
        PhotoUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: ImageBucket
            Events: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: 'jpg'

  ImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: ImageBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Function:
              Fn::Sub: ${ProcessorFunction.Arn}
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: 'jpeg'
          -
            Function:
              Fn::Sub: ${ProcessorFunction.Arn}
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: 'png'
          -
            Function:
              Fn::Sub: ${ProcessorFunction.Arn}
            Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: 'tiff'

  TextTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: TextTableName
      AttributeDefinitions:
        -
          AttributeName: "ObjectPath"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ObjectPath"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Reason
          Value: LambdaOCR

